#: import utils kivy.utils

<HomeScreen>:

    GridLayout:
        size: root.size
        cols:1
        spacing:10
        Label:
            bold: True
            text: "ready to lewk kewl?"
            font_size: 55



        GridLayout:

            cols:4
            Image:
                source: "cher.png"

            ImageButton:
                source: "flaticon-yes.png"
                size:


